### ISSUE TITLE
Missing Response Headers Issue in openapi3-typescript-codegen

### ISSUE THREAD

**Issue by gpiedimonte** [foxel/openapi3-typescript-codegen#8]
**Issue Description:**
I am using openapi3-typescript-codegen to generate TypeScript code for a client API based on a specific OpenAPI 3.0 schema. I have noticed that when making a request to a REST API that returns either a body or only an HTTP status code, the obtained response header is always an empty string ("").

**Steps to Reproduce:**
Generate TypeScript code using openapi3-typescript-codegen and axios from an OpenAPI 3.0 schema that includes endpoints with either a body or only an HTTP status code.
Use the generated code to make a request to an endpoint that returns either a body or only an HTTP status code.
Retrieve the response from the API call and access the response header.

**Expected Behavior:**
The response header should contain the corresponding HTTP headers sent by the server.

**Current Behavior:**
The response header is returned as an empty string ("").

**Additional Information:**
I am using version 0.23 of openapi3-typescript-codegen.
I have verified the API endpoint using external tools (e.g., curl) and confirmed that the header is present in the HTTP response.
The issue occurs only when the API endpoint returns either a body or only an HTTP status code. When the endpoint returns both a body and an HTTP status code, the header is correctly returned.

**Suggestions to Resolve the Issue:**
It would be helpful to implement the functionality to retrieve the response headers even when the API endpoint returns either a body or only an HTTP status code. This would ensure greater consistency and completeness in obtaining response information.

Thank you for your attention and for your work on openapi3-typescript-codegen.

**Comment by foxel** [comment]
Hello @gpiedimonte . Thanks for your input.

Art first glance I don't see where the header can be lost. I want to debug the case, is there any example endpoint and definition files you can provide?

**Comment by gpiedimonte** [comment]
@foxel Sorry I've seen your reply to late. I don't have more an example or an endpoint. Sorry
